# Generated by Django 5.0.2 on 2024-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curriculam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=7)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.FloatField()),
                ('course_class_time_per_week_in_hours', models.FloatField()),
                ('course_contents', models.TextField()),
            ],
        ),
    ]
