# Generated by Django 5.0.2 on 2024-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculam',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
