# Generated by Django 5.0.2 on 2024-03-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_curriculam_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.FileField(upload_to='')),
            ],
        ),
    ]
