# Generated by Django 5.0.2 on 2024-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adjunctfaculty_and_guestteacher_allocatedroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=50)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo_bisemester',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo_bisemester',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo_trisemester',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo_trisemester',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=50),
        ),
    ]
