# Generated by Django 5.0.2 on 2024-05-12 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_semester_alter_studentinfo_bisemester_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculam',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.semester'),
            preserve_default=False,
        ),
    ]
