# Generated by Django 5.0.2 on 2024-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240512_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo_Diploma_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=50)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=50)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='StudentInfo_BiSemester',
            new_name='StudentInfo_HSC_Intake',
        ),
        migrations.DeleteModel(
            name='StudentInfo_TriSemester',
        ),
    ]
