# Generated by Django 5.0.2 on 2024-05-14 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_classslot_room_allocation_to_diploma_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDaysWithSLots_Diploma_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50)),
                ('slots', models.ManyToManyField(related_name='classdayswithslots', to='core.classslot')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculam_Diploma_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.FloatField()),
                ('course_class_time_per_week_in_hours', models.FloatField()),
                ('course_contents', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomacourses', to='core.studentinfo_diploma_intake')),
            ],
        ),
    ]
