# Generated by Django 5.0.2 on 2024-05-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_classdayswithslots_diploma_intake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('H', 'Head'), ('P', 'Professor'), ('AsP', 'Associate Professor'), ('AP', 'Assistant Professor'), ('SL', 'Senior Lecturer'), ('L', 'Lecturer'), ('G', 'Guest')], max_length=50)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('ce', 'CE'), ('ba', 'BA'), ('law', 'Law'), ('ell', 'ELL'), ('ds', 'DS'), ('economics', 'Economics'), ('sociology', 'Sociology'), ('ph', 'PH')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_Allocation_Diploma_Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructorAllocation', to='core.curriculam_diploma_intake')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructorAllocation', to='core.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='AdjunctFaculty_and_GuestTeacher',
        ),
        migrations.DeleteModel(
            name='FacultyMember',
        ),
    ]
